server:
  port: 8771

spring:
  application:
    name: eureka-client
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://localhost:8761/eureka/}

