server:
  port: 8772

spring:
  application:
    name: product-server
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://localhost:8761/eureka/}

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
