spring:
  application:
    name: zuul-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/zipkin/


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_LIST:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 30


zuul:
  sensitive-headers:
  ignored-services: '*'
  routes:
    client:
      path: /api/client/**
      service-id: EUREKA-CLIENT
      strip-prefix: false
    product:
      path: /api/product/**
      service-id: PRODUCT-SERVER
      strip-prefix: false

ribbon:
  ConnectionTimeout: 5000
  ReadTimeout: 2000
